In [2]:
import numpy as np


In [ ]:
A=np.arange(1,13).reshape(4,3)
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
A=np.linspace(50,100,12).reshape(4,3)
print(A)

[[ 50.          54.54545455  59.09090909]
 [ 63.63636364  68.18181818  72.72727273]
 [ 77.27272727  81.81818182  86.36363636]
 [ 90.90909091  95.45454545 100.        ]]


In [ ]:
#reshape-changes needs aving in another variable
#resize-changes the shape of original array
B=np.array([10,20,30,40,50,60,70,80]).reshape(2,2,2)
print(B)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [3]:
B=np.array([10,20,30,40,50,60,70,80,90,100,110,120])
B.resize(2,2,3)
print(B)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]


In [ ]:
#adding array elements
#subtracting array elements
A=np.array([35,78,12,56,65,90.8,24.6])
B=np.array([12,56,90,62,89,25.5,78.5])
c=A-B
print(c)
print(A.max())#It accepts only int and float data types
print(A.min())#It accepts only int and float data types
print(A+B)

[ 23.   22.  -78.   -6.  -24.   65.3 -53.9]
90.8
12.0
[ 47.  134.  102.  118.  154.  116.3 103.1]


In [ ]:
#multiplication of array elements
A=np.array([35,78,12,56]).reshape(2,2)
B=np.array([12,56,90,62]).reshape(2,2)
C=A@B#matrix multiplication
c=A.dot(B)#both formulas for matrix multiplication
print(A)
print(B)
print(C)

[[35 78]
 [12 56]]
[[12 56]
 [90 62]]
[[7440 6796]
 [5184 4144]]


In [ ]:
A=np.array([35,78,12,56]).reshape(2,2)
print(A)
print("--------------------------")
print(A.max(axis=0))#if axis is given as 0 then it gives the column which has highest number among every columns
print("--------------------------")
print(A.max(axis=1))#if axis is given as 1 then it gives the row which has highest number among every row
print("--------------------------")
print(A.min(axis=0))#if axis is given as 0 then it gives the column which has lower number among every columns
print("--------------------------")
print(A.min(axis=1))#if axis is given as 1 then it gives the row which has lower number among every row

[[35 78]
 [12 56]]
--------------------------
[35 78]
--------------------------
[78 56]
--------------------------
[12 56]
--------------------------
[35 12]


In [ ]:
#joining the arrays
A=np.array([35,78,12,56]).reshape(2,2)
B=np.array([12,56,90,62]).reshape(2,2)
print(A)
print("--------------")
print(B)
print("--------------")
print("After vertically stacking the arrays")
print(np.vstack((A,B)))
print("--------------")
print("After horizontally stacking stacking the arrays")
print(np.hstack((A,B)))
print("--------------")
print(np.stack((A,B),axis=0))



[[35 78]
 [12 56]]
--------------
[[12 56]
 [90 62]]
--------------
After vertically stacking the arrays
[[35 78]
 [12 56]
 [12 56]
 [90 62]]
--------------
After horizontally stacking stacking the arrays
[[35 78 12 56]
 [12 56 90 62]]
--------------
[[[35 78]
  [12 56]]

 [[12 56]
  [90 62]]]


In [ ]:
A=np.arange(30).reshape(2,3,5)
print(A)
print("After stack")
print(np.dstack(A))#no. of rows -->no of groups
#no of col in every group --> no of rows in every group

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
After stack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#splitting arrays
A=np.arange(100).reshape(10,10)
print(A)
print("After splitting")
print(np.vsplit(A,5))
print("----------")
print(np.vsplit(A,(1,3,7)))
print("----------")
print(np.hsplit(A,2))
print("----------")
print(np.hsplit(A,(1,3,7,9)))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
After splitting
[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]), array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]), array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]), array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]]), array([[80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]
----------
[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]),

In [ ]:
A=np.array([12,6,23,45,38,56,68,79,82,92,66,33]).reshape(3,4)
print(A)
print(A.argmax(axis=0))
print(A.argmax(axis=1))
print(A.argmin(axis=0))
print(A.argmin(axis=1))

[[12  6 23 45]
 [38 56 68 79]
 [82 92 66 33]]
[2 2 1 1]
[3 3 1]
[0 0 0 2]
[1 0 3]


In [ ]:
#mean,median,std,var
A=np.array([24,6,34,67,89,54])
print("Mean:",np.mean(A))
print("Median:",np.median(A))
print("Standard deviation",np.std(A))
print("Variance:",np.var(A))

Mean: 45.666666666666664
Median: 44.0
Standard deviation 27.632509034750274
Variance: 763.5555555555555


In [ ]:
#trigonometry
A=np.pi #pi=180
print(A)#radians

3.141592653589793


In [ ]:
B=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])
print(B)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
np.rad2deg(A)

180.0

In [ ]:
print(np.rad2deg(B))

[ 45.  60.  90. 180.]


In [ ]:
C=np.array([30,45,60,23,87,56])
D=np.deg2rad(C)
print(D)

[0.52359878 0.78539816 1.04719755 0.40142573 1.51843645 0.97738438]


In [ ]:
np.sin(C)

array([-0.98803162,  0.85090352, -0.30481062, -0.8462204 , -0.82181784,
       -0.521551  ])

In [ ]:
np.cos(C)

array([ 0.15425145,  0.52532199, -0.95241298, -0.53283302,  0.56975033,
        0.85322011])

In [ ]:
np.tan(C)


array([-6.4053312 ,  1.61977519,  0.32004039,  1.58815308, -1.44241747,
       -0.61127369])

In [ ]:
np.arcsin(1)  #sin^-1

1.5707963267948966

In [ ]:
np.arccos(1) #cos^-1

0.0

In [ ]:
np.arctan(1) #tan^-1

0.7853981633974483

In [ ]:
a=6
b=4
print(np.hypot(a,b)) #hypotenuse

7.211102550927978


In [ ]:
A=np.array([90,3,45,21,34,90,21])
print(np.where(A==21))

(array([3, 6]),)


In [ ]:
A=np.array([90,3,45,21,34,90,21])
print(np.where(A%2==0))#even

(array([0, 4, 5]),)


In [ ]:
A=np.array([90,3,45,21,34,90,21])
print(np.where(A>25))#returns the index number of ele greater than 25

(array([0, 2, 4, 5]),)


In [ ]:
A=np.array([3,12,21,34,45,90,91])
print(np.searchsorted(A,45))


4


In [ ]:
#Linear algebra and Ufunc
A=np.array([6,24,60,12,18])
B=np.array([6,4,10,5,8])
print(np.add(A,B))
print(np.subtract(A,B))
print(np.diff(A))#difference gives the differene between prev and cuurent no
print(np.multiply(A,B))
print(np.divide(A,B))
print(np.divmod(A,B))

[12 28 70 17 26]
[ 0 20 50  7 10]
[ 18  36 -48   6]
[ 36  96 600  60 144]
[1.   6.   6.   2.4  2.25]
(array([1, 6, 6, 2, 2]), array([0, 0, 0, 2, 2]))


In [ ]:
#set operations
A=np.array([1,2,3,4,5])
B=np.array([4,5,6,7,8])
print(np.union1d(A,B))
print(np.intersect1d(A,B))
print(np.setdiff1d(A,B))


[1 2 3 4 5 6 7 8]
[4 5]
[1 2 3]


In [ ]:
#Rounding
a=np.trunc([-3.1678,4.1789])#It deletes the decimal part
print(a)
b=np.fix([-3.1678,4.1789])#it makes deciaml part as 0
print(b)
c=np.around([-3.1678,4.1789])
print(c)
d=np.around([-3.1678,4.1789])
print(d)
e=np.floor([-3.1678,4.1789])
print(e)
f=np.ceil([-3.1678,4.1789])
print(f)
g=np.round([2.3,4,5.6])
print(np.cumsum(g))
f=np.round([2.3,4,5.6])
print(np.cumprod(f))

[-3.  4.]
[-3.  4.]
[-3.  4.]
[-3.  4.]
[-4.  4.]
[-3.  5.]
[ 2.  6. 12.]
[ 2.  8. 48.]


In [ ]:
print(np.lcm(45,90))
print(np.gcd(12,34))
A=np.array([34,56])
print(np.lcm.reduce(A))
print(np.gcd.reduce(A))

90
2
952
2


In [ ]:
A=np.array([[1,2],[3,4]])
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
from numpy import random as rd

In [ ]:
b=rd.rand()#default value b/w 0 to 0.99
A=rd.rand(25)#rand(no. of numbers)
print(A)
print(b)

[0.8643559  0.71888086 0.98328938 0.49705967 0.23403619 0.71021319
 0.33723598 0.34406921 0.9767572  0.7941935  0.03251487 0.73017367
 0.44781647 0.31945575 0.0261674  0.41138531 0.13995176 0.22533472
 0.66235475 0.88556628 0.2983605  0.33836948 0.15798415 0.74167859
 0.88758968]
0.619895281172669


In [ ]:
A=rd.randint(10)#randint(limit)-it gives the value in that limit
print(A)

8


In [ ]:
A=rd.randint(50,size=8)
B=rd.randint(60,size=(6,6))
print(A)
print(B)

[13  9  8 43  3 21 40 39]
[[15 43  3  8 56 10]
 [46  4 29 49 36 20]
 [16 58  5 39  1 45]
 [43 56 33  4 54 22]
 [36 35 47 53 17 21]
 [27 11 42 23  7 52]]


In [ ]:
A=np.array([1,6,8])
B=np.array([5,2,9])
#1*5+6*2+8*9
print(np.inner(A,B))
#[[1*5 1*2 1*9 6*5 6*2 6*9 8*5 8*2 8*9]]
print(np.outer(A,B))
print(np.cross(A,B))#det

89
[[ 5  2  9]
 [30 12 54]
 [40 16 72]]
[ 38  31 -28]
